import type { Metadata } from "next";
import { Inter, Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import "swiper/css";
import "swiper/css/pagination";
import BackgroundSquares from "@/components/background/BackgroundSquares";
import { Toaster } from "sonner";

const inter = Inter({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
});
export const poppins = Poppins({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
});
export const playfairDisplay = Playfair_Display({
  weight: ["400", "500", "600"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Shathi Paul Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased bg-secondary text-primary`}
      >
        <BackgroundSquares />
        <Toaster richColors={true} />
        {children}
      </body>
    </html>
  );
}
